<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFvsViQ7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFvsViQ7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFvsViQ7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFvsViQ7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFvsViQ7\App_KernelDevDebugContainer([
    'container.build_hash' => 'FvsViQ7',
    'container.build_id' => '6a3fd91c',
    'container.build_time' => 1612113490,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFvsViQ7');
